# Generated by Django 2.1.4 on 2019-10-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '用例信息',
                'verbose_name': '用例信息',
                'db_table': 'api_case',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('private_key', models.CharField(max_length=50, verbose_name='私钥')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '测试环境',
                'verbose_name': '测试环境',
                'db_table': 'api_environment',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('if_id', models.AutoField(primary_key=True, serialize=False)),
                ('if_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('method', models.CharField(max_length=4, verbose_name='请求方式')),
                ('data_type', models.CharField(max_length=4, verbose_name='数据类型')),
                ('is_sign', models.IntegerField(verbose_name='签名')),
                ('request_header_param', models.TextField(verbose_name='请求头部')),
                ('request_body_param', models.TextField(verbose_name='请求数据')),
                ('response_header_param', models.TextField(verbose_name='返回头部')),
                ('response_body_param', models.TextField(verbose_name='返回数据')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '接口信息',
                'verbose_name': '接口信息',
                'db_table': 'api_interface',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50, verbose_name='计划名称')),
                ('content', models.TextField(verbose_name='计划内容')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Environment', verbose_name='测试环境')),
            ],
            options={
                'verbose_name_plural': '计划信息',
                'verbose_name': '计划信息',
                'db_table': 'api_plan',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '项目信息',
                'verbose_name': '项目信息',
                'db_table': 'api_project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255, verbose_name='计划名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('case_num', models.IntegerField(null=True, verbose_name='用例')),
                ('pass_num', models.IntegerField(null=True, verbose_name='通过')),
                ('fail_num', models.IntegerField(null=True, verbose_name='失败')),
                ('error_num', models.IntegerField(null=True, verbose_name='错误')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Plan', verbose_name='计划名称')),
            ],
            options={
                'verbose_name_plural': '报告信息',
                'verbose_name': '报告信息',
                'db_table': 'api_report',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=50, verbose_name='签名')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '签名信息',
                'verbose_name': '签名信息',
                'db_table': 'api_sign',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Sign', verbose_name='签名信息'),
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='interface',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_platform.Project', verbose_name='所属项目'),
        ),
    ]
