# Generated by Django 2.1.4 on 2019-10-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('label', models.CharField(max_length=150, unique=True, verbose_name='标签')),
                ('value', models.CharField(max_length=150, unique=True, verbose_name='键值')),
                ('type', models.CharField(max_length=150, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '字典',
                'verbose_name': '字典',
                'db_table': 'base_dictionary',
            },
        ),
        migrations.CreateModel(
            name='user_platfrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='地址')),
                ('identification', models.CharField(blank=True, max_length=50, null=True, verbose_name='证件号')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_platform.base_dictionary', verbose_name='证件类型')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
                'db_table': 'user_platfrom',
            },
        ),
    ]
